[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.x"
  NPM_VERSION = "8.x"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"
  REACT_APP_API_URL = "https://medical-service-backend-eg8t.onrender.com"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 