[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = "false"
  NODE_VERSION = "16"
  REACT_APP_API_URL = "https://medical-service-backend-eg8t.onrender.com" 