[build]
  base = "frontend"
  command = "rm -rf node_modules && npm cache clean --force && npm install --legacy-peer-deps && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.x"
  NPM_VERSION = "9.x"
  CI = "false"
  NODE_OPTIONS = "--openssl-legacy-provider --max_old_space_size=4096"
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_PREFLIGHT_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 