[build]
  base = "frontend"
  command = "CI=false npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.x"
  NPM_VERSION = "9.x"
  CI = "false"
  NODE_OPTIONS = "--openssl-legacy-provider --max_old_space_size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 