[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && NODE_OPTIONS='--openssl-legacy-provider --max_old_space_size=4096' npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = "false"
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.5.0"
  NODE_OPTIONS = "--max_old_space_size=4096"
  REACT_APP_API_URL = "https://medical-service-backend-eg8t.onrender.com" 