services:
  - type: web
    name: medical-service-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PAYPAL_CLIENT_ID
        sync: false
    nodeVersion: 16.x
