services:
  - type: web
    name: medical-service-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: mongodb+srv://rabita1234:tashfiq0907027@cluster0.qrp6h.mongodb.net/medical?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    runtime: node
    nodeVersion: 18.x
