export const AMBULANCE_REQUEST = "AMBULANCE_REQUEST";
export const AMBULANCE_SUCCESS = "AMBULANCE_SUCCESS";
export const AMBULANCE_FAIL = "AMBULANCE_FAIL";

export const AMBULANCE_DELETE_REQUEST = "AMBULANCE_DELETE_REQUEST";
export const AMBULANCE_DELETE_SUCCESS = "AMBULANCE_DELETE_SUCCESS";
export const AMBULANCE_DELETE_FAIL = "AMBULANCE_DELETE_FAIL";

export const AMBULANCE_CREATE_REQUEST = "SPECI_CREATE_REQUEST";
export const AMBULANCE_CREATE_SUCCESS = "SPECIALIST_CREATE_SUCCESS";
export const AMBULANCE_CREATE_FAIL = "SPECIALIST_CREATE_FAIL";

export const AMBULANCE_DETAILS_REQUEST = "AMBULANCE_DETAILS_REQUEST";
export const AMBULANCE_DETAILS_SUCCESS = "AMBULANCE_DETAILS_SUCCESS";
export const AMBULANCE_DETAILS_FAIL = "AMBULANCE_DETAILS_FAIL";

export const AMBULANCE_DETAILS_RESET = "AMBULANCE_DETAILS_RESET";

export const AMBULANCE_UPDATE_REQUEST = "AMBULANCE_UPDATE_REQUEST";
export const AMBULANCE_UPDATE_SUCCESS = "AMBULANCE_UPDATE_SUCCESS";
export const AMBULANCE_UPDATE_FAIL = "AMBULANCE_UPDATE_FAIL";
export const AMBULANCE_UPDATE_RESET = "AMBULANCE_UPDATE_RESET";
