export const EMERGENCY_DOCTOR_CREATE_REQUEST =
  "EMERGENCY_DOCTOR_CREATE_REQUEST";
export const EMERGENCY_DOCTOR_CREATE_SUCCESS =
  "EMERGENCY_DOCTOR_CREATE_SUCCESS";
export const EMERGENCY_DOCTOR_CREATE_FAIL = "EMERGENCY_DOCTOR_CREATE_FAIL";

export const EMERGENCY_DOCTOR_LIST_REQUEST = "EMERGENCY_DOCTOR_LIST_REQUEST";
export const EMERGENCY_DOCTOR_LIST_SUCCESS = "EMERGENCY_DOCTOR_LIST_SUCCESS";
export const EMERGENCY_DOCTOR_LIST_FAIL = "EMERGENCY_DOCTOR_LIST_FAIL";
export const EMERGENCY_DOCTOR_LIST_RESET = "EMERGENCY_DOCTOR_LIST_RESET";

export const EMERGENCY_DOCTOR_DETAILS_REQUEST =
  "EMERGENCY_DOCTOR_DETAILS_REQUEST";
export const EMERGENCY_DOCTOR_DETAILS_SUCCESS =
  "EMERGENCY_DOCTOR_DETAILS_SUCCESS";
export const EMERGENCY_DOCTOR_DETAILS_FAIL = "EMERGENCY_DOCTOR_DETAILS_FAIL";
export const EMERGENCY_DOCTOR_DETAILS_RESET = "EMERGENCY_DOCTOR_DETAILS_RESET";

export const EMERGENCY_DOCTOR_UPDATE_REQUEST =
  "EMERGENCY_DOCTOR_UPDATE_REQUEST";
export const EMERGENCY_DOCTOR_UPDATE_SUCCESS =
  "EMERGENCY_DOCTOR_UPDATE_SUCCESS";
export const EMERGENCY_DOCTOR_UPDATE_FAIL = "EMERGENCY_DOCTOR_UPDATE_FAIL";
export const EMERGENCY_DOCTOR_UPDATE_RESET = "EMERGENCY_DOCTOR_UPDATE_RESET";
