export const NURSING_PACKAGE_LIST_REQUEST = "NURSING_PACKAGE_LIST_REQUEST";
export const NURSING_PACKAGE_LIST_SUCCESS = "NURSING_PACKAGE_LIST_SUCCESS";
export const NURSING_PACKAGE_LIST_FAIL = "NURSING_PACKAGE_LIST_FAIL";

export const NURSING_PACKAGE_TYPE_REQUEST = "NURSING_PACKAGE_TYPE_REQUEST";
export const NURSING_PACKAGE_TYPE_SUCCESS = "NURSING_PACKAGE_TYPE_SUCCESS";
export const NURSING_PACKAGE_TYPE_FAIL = "NURSING_PACKAGE_TYPE_FAIL";

export const NURSING_PACKAGE_SAVE_FORM_REQUEST =
  "NURSING_PACKAGE_SAVE_FORM_REQUEST";
export const NURSING_PACKAGE_SAVE_FORM_SUCCESS =
  "NURSING_PACKAGE_SAVE_FORM_SUCCESS";
export const NURSING_PACKAGE_SAVE_FORM_FAIL = "NURSING_PACKAGE_SAVE_FORM_FAIL";

export const NURSING_PACKAGE_FORM_DATA_REQUEST =
  "NURSING_PACKAGE_FORM_DATA_REQUEST";
export const NURSING_PACKAGE_FORM_DATA_SUCCESS =
  "NURSING_PACKAGE_FORM_DATA_SUCCESS";
export const NURSING_PACKAGE_FORM_DATA_FAIL = "NURSING_PACKAGE_FORM_DATA_FAIL";

export const NURSING_PACKAGE_DATA_BY_ID_REQUEST =
  "NURSING_PACKAGE_DATA_BY_ID_REQUEST";
export const NURSING_PACKAGE_DATA_BY_ID_SUCCESS =
  "NURSING_PACKAGE_DATA_BY_ID_SUCCESS";
export const NURSING_PACKAGE_DATA_BY_ID_FAIL =
  "NURSING_PACKAGE_DATA_BY_ID_FAIL";
