export const MEDICATION_LIST_REQUEST = 'MEDICATION_LIST_REQUEST';
export const MEDICATION_LIST_SUCCESS = 'MEDICATION_LIST_SUCCESS';
export const MEDICATION_LIST_FAIL = 'MEDICATION_LIST_FAIL';

export const MEDICATION_DETAILS_REQUEST = 'MEDICATION_DETAILS_REQUEST';
export const MEDICATION_DETAILS_SUCCESS = 'MEDICATION_DETAILS_SUCCESS';
export const MEDICATION_DETAILS_FAIL = 'MEDICATION_DETAILS_FAIL';

export const MEDICATION_CREATE_REQUEST = 'MEDICATION_CREATE_REQUEST';
export const MEDICATION_CREATE_SUCCESS = 'MEDICATION_CREATE_SUCCESS';
export const MEDICATION_CREATE_FAIL = 'MEDICATION_CREATE_FAIL';
export const MEDICATION_CREATE_RESET = 'MEDICATION_CREATE_RESET';

export const PRESCRIPTION_ORDER_CREATE_REQUEST = 'PRESCRIPTION_ORDER_CREATE_REQUEST';
export const PRESCRIPTION_ORDER_CREATE_SUCCESS = 'PRESCRIPTION_ORDER_CREATE_SUCCESS';
export const PRESCRIPTION_ORDER_CREATE_FAIL = 'PRESCRIPTION_ORDER_CREATE_FAIL';
export const PRESCRIPTION_ORDER_CREATE_RESET = 'PRESCRIPTION_ORDER_CREATE_RESET';

export const PRESCRIPTION_ORDER_LIST_REQUEST = 'PRESCRIPTION_ORDER_LIST_REQUEST';
export const PRESCRIPTION_ORDER_LIST_SUCCESS = 'PRESCRIPTION_ORDER_LIST_SUCCESS';
export const PRESCRIPTION_ORDER_LIST_FAIL = 'PRESCRIPTION_ORDER_LIST_FAIL';

export const PRESCRIPTION_ORDER_DETAILS_REQUEST = 'PRESCRIPTION_ORDER_DETAILS_REQUEST';
export const PRESCRIPTION_ORDER_DETAILS_SUCCESS = 'PRESCRIPTION_ORDER_DETAILS_SUCCESS';
export const PRESCRIPTION_ORDER_DETAILS_FAIL = 'PRESCRIPTION_ORDER_DETAILS_FAIL';

export const PRESCRIPTION_ORDER_STATUS_UPDATE_REQUEST = 'PRESCRIPTION_ORDER_STATUS_UPDATE_REQUEST';
export const PRESCRIPTION_ORDER_STATUS_UPDATE_SUCCESS = 'PRESCRIPTION_ORDER_STATUS_UPDATE_SUCCESS';
export const PRESCRIPTION_ORDER_STATUS_UPDATE_FAIL = 'PRESCRIPTION_ORDER_STATUS_UPDATE_FAIL';
export const PRESCRIPTION_ORDER_STATUS_UPDATE_RESET = 'PRESCRIPTION_ORDER_STATUS_UPDATE_RESET'; 