export const PHYSIOTHERAPY_PACKAGE_LIST_REQUEST =
  "PHYSIOTHERAPY_PACKAGE_LIST_REQUEST";
export const PHYSIOTHERAPY_PACKAGE_LIST_SUCCESS =
  "PHYSIOTHERAPY_PACKAGE_LIST_SUCCESS";
export const PHYSIOTHERAPY_PACKAGE_LIST_FAIL =
  "PHYSIOTHERAPY_PACKAGE_LIST_FAIL";

export const PHYSIOTHERAPY_SAVE_FORM_REQUEST =
  "PHYSIOTHERAPY_SAVE_FORM_REQUEST";
export const PHYSIOTHERAPY_SAVE_FORM_SUCCESS =
  "PHYSIOTHERAPY_SAVE_FORM_SUCCESS";
export const PHYSIOTHERAPY_SAVE_FORM_FAIL = "PHYSIOTHERAPY_SAVE_FORM_FAIL";

export const USER_ORDER_LIST_REQUEST = "USER_ORDER_LIST_REQUEST";
export const USER_ORDER_LIST_SUCCESS = "USER_ORDER_LIST_SUCCESS";
export const USER_ORDER_LIST_FAIL = "USER_ORDER_LIST_FAIL";

export const MARK_PAYMENT_REQUEST = "MARK_PAYMENT_REQUEST";
export const MARK_PAYMENT_SUCCESS = "MARK_PAYMENT_SUCCESS";
export const MARK_PAYMENT_FAIL = "MARK_PAYMENT_FAIL";
