export const SPECIALIST_REQUEST = "SPECIALIST_REQUEST";
export const SPECIALIST_SUCCESS = "SPECIALIST_SUCCESS";
export const SPECIALIST_FAIL = "SPECIALIST_FAIL";

export const SPECIALIST_DELETE_REQUEST = "SPECIALIST_DELETE_REQUEST";
export const SPECIALIST_DELETE_SUCCESS = "SPECIALIST_DELETE_SUCCESS";
export const SPECIALIST_DELETE_FAIL = "SPECIALIST_DELETE_FAIL";

export const SPECIALIST_CREATE_REQUEST = "SPECIALIST_CREATE_REQUEST";
export const SPECIALIST_CREATE_SUCCESS = "SPECIALIST_CREATE_SUCCESS";
export const SPECIALIST_CREATE_FAIL = "SPECIALIST_CREATE_FAIL";

export const SPECIALIST_DETAILS_REQUEST = "SPECIALIST_DETAILS_REQUEST";
export const SPECIALIST_DETAILS_SUCCESS = "SPECIALIST_DETAILS_SUCCESS";
export const SPECIALIST_DETAILS_FAIL = "SPECIALIST_DETAILS_FAIL";

export const SPECIALIST_DETAILS_RESET = "SPECIALIST_DETAILS_RESET";

export const SPECIALIST_UPDATE_REQUEST = "SPECIALIST_UPDATE_REQUEST";
export const SPECIALIST_UPDATE_SUCCESS = "SPECIALIST_UPDATE_SUCCESS";
export const SPECIALIST_UPDATE_FAIL = "SPECIALIST_UPDATE_FAIL";
export const SPECIALIST_UPDATE_RESET = "SPECIALIST_UPDATE_RESET";
