export const TEST_LIST_REQUEST = 'TEST_LIST_REQUEST';
export const TEST_LIST_SUCCESS = 'TEST_LIST_SUCCESS';
export const TEST_LIST_FAIL = 'TEST_LIST_FAIL';

export const TEST_DETAILS_REQUEST = 'TEST_DETAILS_REQUEST';
export const TEST_DETAILS_SUCCESS = 'TEST_DETAILS_SUCCESS';
export const TEST_DETAILS_FAIL = 'TEST_DETAILS_FAIL';

export const TEST_BOOK_REQUEST = 'TEST_BOOK_REQUEST';
export const TEST_BOOK_SUCCESS = 'TEST_BOOK_SUCCESS';
export const TEST_BOOK_FAIL = 'TEST_BOOK_FAIL';
export const TEST_BOOK_RESET = 'TEST_BOOK_RESET';

export const TEST_BOOKING_REQUEST = 'TEST_BOOKING_REQUEST';
export const TEST_BOOKING_SUCCESS = 'TEST_BOOKING_SUCCESS';
export const TEST_BOOKING_FAIL = 'TEST_BOOKING_FAIL';

export const TEST_BOOKING_LIST_REQUEST = 'TEST_BOOKING_LIST_REQUEST';
export const TEST_BOOKING_LIST_SUCCESS = 'TEST_BOOKING_LIST_SUCCESS';
export const TEST_BOOKING_LIST_FAIL = 'TEST_BOOKING_LIST_FAIL';

export const TEST_BOOKING_CANCEL_REQUEST = 'TEST_BOOKING_CANCEL_REQUEST';
export const TEST_BOOKING_CANCEL_SUCCESS = 'TEST_BOOKING_CANCEL_SUCCESS';
export const TEST_BOOKING_CANCEL_FAIL = 'TEST_BOOKING_CANCEL_FAIL';
export const TEST_BOOKING_CANCEL_RESET = 'TEST_BOOKING_CANCEL_RESET';

export const TEST_BOOKING_COMPLETE_REQUEST = 'TEST_BOOKING_COMPLETE_REQUEST';
export const TEST_BOOKING_COMPLETE_SUCCESS = 'TEST_BOOKING_COMPLETE_SUCCESS';
export const TEST_BOOKING_COMPLETE_FAIL = 'TEST_BOOKING_COMPLETE_FAIL';
export const TEST_BOOKING_COMPLETE_RESET = 'TEST_BOOKING_COMPLETE_RESET';

export const TEST_BOOKING_RESCHEDULE_REQUEST = 'TEST_BOOKING_RESCHEDULE_REQUEST';
export const TEST_BOOKING_RESCHEDULE_SUCCESS = 'TEST_BOOKING_RESCHEDULE_SUCCESS';
export const TEST_BOOKING_RESCHEDULE_FAIL = 'TEST_BOOKING_RESCHEDULE_FAIL';

export const TEST_CREATE_REQUEST = 'TEST_CREATE_REQUEST';
export const TEST_CREATE_SUCCESS = 'TEST_CREATE_SUCCESS';
export const TEST_CREATE_FAIL = 'TEST_CREATE_FAIL';
export const TEST_CREATE_RESET = 'TEST_CREATE_RESET';

export const TEST_UPDATE_REQUEST = 'TEST_UPDATE_REQUEST';
export const TEST_UPDATE_SUCCESS = 'TEST_UPDATE_SUCCESS';
export const TEST_UPDATE_FAIL = 'TEST_UPDATE_FAIL';
export const TEST_UPDATE_RESET = 'TEST_UPDATE_RESET';

export const TEST_DELETE_REQUEST = 'TEST_DELETE_REQUEST';
export const TEST_DELETE_SUCCESS = 'TEST_DELETE_SUCCESS';
export const TEST_DELETE_FAIL = 'TEST_DELETE_FAIL';
export const TEST_DELETE_RESET = 'TEST_DELETE_RESET';
