export const TEST_LIST_REQUEST = 'TEST_LIST_REQUEST';
export const TEST_LIST_SUCCESS = 'TEST_LIST_SUCCESS';
export const TEST_LIST_FAIL = 'TEST_LIST_FAIL';

export const TEST_DETAILS_REQUEST = 'TEST_DETAILS_REQUEST';
export const TEST_DETAILS_SUCCESS = 'TEST_DETAILS_SUCCESS';
export const TEST_DETAILS_FAIL = 'TEST_DETAILS_FAIL';

export const TEST_BOOKING_REQUEST = 'TEST_BOOKING_REQUEST';
export const TEST_BOOKING_SUCCESS = 'TEST_BOOKING_SUCCESS';
export const TEST_BOOKING_FAIL = 'TEST_BOOKING_FAIL';

export const TEST_BOOKING_LIST_REQUEST = 'TEST_BOOKING_LIST_REQUEST';
export const TEST_BOOKING_LIST_SUCCESS = 'TEST_BOOKING_LIST_SUCCESS';
export const TEST_BOOKING_LIST_FAIL = 'TEST_BOOKING_LIST_FAIL';

export const TEST_BOOKING_CANCEL_REQUEST = 'TEST_BOOKING_CANCEL_REQUEST';
export const TEST_BOOKING_CANCEL_SUCCESS = 'TEST_BOOKING_CANCEL_SUCCESS';
export const TEST_BOOKING_CANCEL_FAIL = 'TEST_BOOKING_CANCEL_FAIL';

export const TEST_BOOKING_RESCHEDULE_REQUEST = 'TEST_BOOKING_RESCHEDULE_REQUEST';
export const TEST_BOOKING_RESCHEDULE_SUCCESS = 'TEST_BOOKING_RESCHEDULE_SUCCESS';
export const TEST_BOOKING_RESCHEDULE_FAIL = 'TEST_BOOKING_RESCHEDULE_FAIL';
