export const TEST_CATEGORY_LIST_REQUEST = 'TEST_CATEGORY_LIST_REQUEST';
export const TEST_CATEGORY_LIST_SUCCESS = 'TEST_CATEGORY_LIST_SUCCESS';
export const TEST_CATEGORY_LIST_FAIL = 'TEST_CATEGORY_LIST_FAIL'; 